---
abstract: 'move js loading to the end of the document'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-JSLoader
requires:
  Mojolicious: 4.0
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-JSLoader/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-JSLoader
  repository: http://github.com/reneeb/Mojolicious-Plugin-JSLoader.git
version: 0.01
